In [39]:
import pandas as pd
import seaborn as sns

In [40]:
#Reading dataset 
ds_url = 'all_data_M_2023.xlsx'
ds = pd.read_excel(ds_url)
pd.set_option('display.max_columns', None)

In [45]:
ds.head(10)

,AREA,AREA_TITLE,AREA_TYPE,PRIM_STATE,NAICS,NAICS_TITLE,I_GROUP,OWN_CODE,OCC_CODE,OCC_TITLE,O_GROUP,TOT_EMP,EMP_PRSE,JOBS_1000,LOC_QUOTIENT,PCT_TOTAL,PCT_RPT,H_MEAN,A_MEAN,MEAN_PRSE,H_PCT10,H_PCT25,H_MEDIAN,H_PCT75,H_PCT90,A_PCT10,A_PCT25,A_MEDIAN,A_PCT75,A_PCT90,ANNUAL,HOURLY
0,99,U.S.,1,US,000000,Cross-industry,cross-industry,1235,00-0000,All Occupations,total,151853870,0,NaN,NaN,NaN,NaN,31.48,65470,0.3,13.97,17.14,23.11,37.01,58.4,29050,35660,48060,76980,121470,NaN,NaN
1,99,U.S.,1,US,000000,Cross-industry,cross-industry,1235,11-0000,Management Occupations,major,10495770,0.4,NaN,NaN,NaN,NaN,66.23,137750,0.5,26.23,37.66,56.19,81.29,111.36,54550,78330,116880,169090,231620,NaN,NaN
2,99,U.S.,1,US,000000,Cross-industry,cross-industry,1235,11-1000,Top Executives,minor,3751510,0.4,NaN,NaN,NaN,NaN,65.43,136100,0.9,22.31,31.81,49.74,79.57,#,46400,66170,103460,165500,#,NaN,NaN
3,99,U.S.,1,US,000000,Cross-industry,cross-industry,1235,11-1010,Chief Executives,broad,211230,1.4,NaN,NaN,NaN,NaN,124.47,258900,0.7,38.46,62.9,99.37,#,#,80000,130840,206680,#,#,NaN,NaN
4,99,U.S.,1,US,000000,Cross-industry,cross-industry,1235,11-1011,Chief Executives,detailed,211230,1.4,NaN,NaN,NaN,NaN,124.47,258900,0.7,38.46,62.9,99.37,#,#,80000,130840,206680,#,#,NaN,NaN
5,99,U.S.,1,US,000000,Cross-industry,cross-industry,1235,11-1020,General and Operations Managers,broad,3507810,0.4,NaN,NaN,NaN,NaN,62.18,129330,0.9,22.28,31.34,48.69,77.06,111.59,46340,65180,101280,160290,232110,NaN,NaN
6,99,U.S.,1,US,000000,Cross-industry,cross-industry,1235,11-1021,General and Operations Managers,detailed,3507810,0.4,NaN,NaN,NaN,NaN,62.18,129330,0.9,22.28,31.34,48.69,77.06,111.59,46340,65180,101280,160290,232110,NaN,NaN
7,99,U.S.,1,US,000000,Cross-industry,cross-industry,1235,11-1030,Legislators,broad,32460,1.7,NaN,NaN,NaN,NaN,*,68140,1.3,*,*,*,*,*,21010,28810,47290,82200,129510,True,NaN
8,99,U.S.,1,US,000000,Cross-industry,cross-industry,1235,11-1031,Legislators,detailed,32460,1.7,NaN,NaN,NaN,NaN,*,68140,1.3,*,*,*,*,*,21010,28810,47290,82200,129510,True,NaN
9,99,U.S.,1,US,000000,Cross-industry,cross-industry,1235,11-2000,"Advertising, Marketing, Promotions, Public Rel...",minor,1070030,1.5,NaN,NaN,NaN,NaN,76.9,159960,0.3,33.26,47.68,67.23,96.15,#,69170,99180,139850,199990,#,NaN,NaN

In [46]:
ds.tail(10)

,AREA,AREA_TITLE,AREA_TYPE,PRIM_STATE,NAICS,NAICS_TITLE,I_GROUP,OWN_CODE,OCC_CODE,OCC_TITLE,O_GROUP,TOT_EMP,EMP_PRSE,JOBS_1000,LOC_QUOTIENT,PCT_TOTAL,PCT_RPT,H_MEAN,A_MEAN,MEAN_PRSE,H_PCT10,H_PCT25,H_MEDIAN,H_PCT75,H_PCT90,A_PCT10,A_PCT25,A_MEDIAN,A_PCT75,A_PCT90,ANNUAL,HOURLY
413317,4100006,Coast Oregon nonmetropolitan area,6,OR,000000,Cross-industry,cross-industry,1235,53-7199,"Material Moving Workers, All Other",detailed,130,10.7,1.12,7.09,NaN,NaN,24.22,50370,1.6,18.5,21.64,24.72,27.19,27.52,38480,45000,51420,56560,57250,NaN,NaN
413318,4700001,West Tennessee nonmetropolitan area,6,TN,000000,Cross-industry,cross-industry,1235,53-7199,"Material Moving Workers, All Other",detailed,40,13.5,0.288,1.83,NaN,NaN,20.27,42170,5,17.99,18.43,18.43,23.06,23.84,37430,38330,38330,47960,49590,NaN,NaN
413319,4700004,East Tennessee nonmetropolitan area,6,TN,000000,Cross-industry,cross-industry,1235,53-7199,"Material Moving Workers, All Other",detailed,40,30.4,0.308,1.95,NaN,NaN,19.05,39620,6.1,14.53,14.53,19.64,23.13,23.13,30220,30220,40860,48110,48110,NaN,NaN
413320,4800002,North Texas Region of Texas nonmetropolitan area,6,TX,000000,Cross-industry,cross-industry,1235,53-7199,"Material Moving Workers, All Other",detailed,140,7.3,0.497,3.15,NaN,NaN,20.2,42010,1.1,15.21,17.72,21.53,22.77,23.91,31630,36860,44780,47350,49730,NaN,NaN
413321,4800004,Hill Country Region of Texas nonmetropolitan area,6,TX,000000,Cross-industry,cross-industry,1235,53-7199,"Material Moving Workers, All Other",detailed,90,21.6,0.446,2.83,NaN,NaN,14.5,30150,3.4,10.46,11.29,13.85,16.19,20.63,21750,23480,28820,33680,42920,NaN,NaN
413322,4800006,Coastal Plains Region of Texas nonmetropolitan...,6,TX,000000,Cross-industry,cross-industry,1235,53-7199,"Material Moving Workers, All Other",detailed,30,38.3,0.229,1.45,NaN,NaN,17.11,35600,6.7,14.27,14.86,17.45,18.74,20.54,29680,30910,36290,38980,42720,NaN,NaN
413323,5500001,Northwestern Wisconsin nonmetropolitan area,6,WI,000000,Cross-industry,cross-industry,1235,53-7199,"Material Moving Workers, All Other",detailed,90,36.4,1.889,11.97,NaN,NaN,16.65,34640,4.4,13.35,14.51,15.39,19.25,22,27770,30180,32020,40040,45760,NaN,NaN
413324,5500002,Northeastern Wisconsin nonmetropolitan area,6,WI,000000,Cross-industry,cross-industry,1235,53-7199,"Material Moving Workers, All Other",detailed,140,27.6,0.703,4.45,NaN,NaN,16.22,33740,4.8,9.76,12.06,14.11,18.29,26.99,20290,25080,29350,38050,56130,NaN,NaN
413325,5500003,South Central Wisconsin nonmetropolitan area,6,WI,000000,Cross-industry,cross-industry,1235,53-7199,"Material Moving Workers, All Other",detailed,90,21.8,0.441,2.8,NaN,NaN,17.62,36650,3.2,13.64,15.71,15.94,18.55,20.54,28380,32680,33150,38590,42730,NaN,NaN
413326,5500004,Western Wisconsin nonmetropolitan area,6,WI,000000,Cross-industry,cross-industry,1235,53-7199,"Material Moving Workers, All Other",detailed,**,**,**,**,NaN,NaN,20.04,41690,4.5,10.64,13.84,16.42,26.99,29.69,22130,28790,34160,56130,61740,NaN,NaN